# Generated by Django 3.2.8 on 2021-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='difficulty',
            field=models.CharField(choices=[('novice', 'NOVICE'), ('intermediate', 'INTERMEDIATE'), ('advanced', 'ADVANCED')], default='novice', max_length=12),
        ),
    ]
