# Generated by Django 3.2.8 on 2022-01-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_auto_20211114_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='difficulty',
            field=models.CharField(choices=[('NOVICE', 'novice'), ('INTERMEDIATE', 'intermediate'), ('ADVANCED', 'advanced')], default='NOVICE', max_length=12),
        ),
    ]
